export const UPDATE_GRIDENT_COLOR_MODE = "UPDATE_GRIDENT_COLOR_MODE";

export const UPDATE_GRIDENT_PRECISION = "UPDATE_GRIDENT_PRECISION";

export const UPDATE_GRIDENT_ANGLE = "UPDATE_GRIDENT_ANGLE";

export const UPDATE_GRIDENT_COLORS = "UPDATE_GRIDENT_COLORS";
